on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - main
      - sonar-test
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    # - name: Install dependencies
    #   run: yarn
    # - name: Test and coverage
    #   run: yarn jest --coverage
    - name:  SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      # with:
      #    args: >
      #     -Dsonar.organization=vishalsathwaraa
      #     -Dsonar.projectKey=vishalsathwaraa_sonar-cloud-test
      #     -Dsonar.sources=src
      #     -Dsonar.tests=src
      #     -Dsonar.test.inclusions=src/**/__tests__/**
      #     -Dsonar.exclusions=src/**/__tests__/**
      #     -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
      #     -Dsonar.coverage.exclusions=__mocks__/**,.storybook/**,src/stories/**,src/types/**
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}